version: '3'
services:
  db:
    image: mariadb:10.6
    container_name: backend-db
    environment:
      - MARIADB_DATABASE=meltroad
      - MARIADB_USER=meltroad
      - MARIADB_PASSWORD=nicegame14
      - MARIADB_ROOT_PASSWORD=nicegame14
      - MARIADB_MYSQL_LOCALHOST_USER=1
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 20s
      timeout: 5s
      retries: 3
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint: [ "./docker-entrypoint.sh" ]
    platform: linux/arm64
    volumes:
      - .:/home/www/backend/
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    tty: true
    links:
      - "db:backend-db"