# Generated by Django 5.1 on 2024-08-11 14:44

import django.db.models.deletion
import meltroad_backend.post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='category.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_image',
            field=models.ImageField(upload_to=meltroad_backend.post.models.upload_post_meta_image),
        ),
    ]
