# Generated by Django 5.1 on 2024-08-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_date_published_alter_post_meta_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
